# Generated by Django 3.1.7 on 2021-05-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='img',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
