# Generated by Django 3.1.7 on 2021-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='video',
            field=models.CharField(default='', max_length=300),
        ),
    ]
