# Generated by Django 3.1.7 on 2021-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_auto_20210509_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='para3',
            field=models.TextField(default=''),
        ),
    ]
