# Generated by Django 3.1.7 on 2021-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0006_jobs_para3'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='jobs',
            name='price',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
